export const GET_FORMS_REQ = "GET_FORMS_REQ";
export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const ADD_FORM = "ADD_FORM";
export const UPDATE_FORM = "UPDATE_FORM";
export const DELETE_FORM = "DELETE_FORM";
export const ADD_FORMS_SUCCESS = "ADD_FORMS_SUCCESS";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
